on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  datasets_gen_daily:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - uses: oven-sh/setup-bun@v1
        name: setup bun
        with:
          bun-version: 1.0.22

      - name: install python dependencies
        run: pip install -r scripts/data/common/killed-in-gaza/requirements.txt

      - name: install dependencies
        run: bun install

      - name: run scripts & diff
        run: |
          python scripts/data/common/killed-in-gaza/generate_killed_list.py
          mkdir -p ci-tmp
          bun run gen-killed
          git diff killed-in-gaza.json > ci-tmp/killed-in-gaza.diff

      - name: upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: killed-in-gaza-log
          path: ci-tmp/killed-in-gaza-log.txt

      - name: upload diff artifact
        uses: actions/upload-artifact@v4
        with:
          name: killed-in-gaza-diff
          path: ci-tmp/killed-in-gaza.diff

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        name: commit changes
        with:
          message: "daily: update for ${{ steps.commitvars.outputs.currentdate }}"
          add: '["killed-in-gaza.json", "killed-in-gaza.min.json"]'
          push: true
