on: workflow_dispatch

jobs:
  datasets_gen_daily:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - uses: oven-sh/setup-bun@v1
        name: setup bun
        with:
          bun-version: 1.0.22

      - name: install python dependencies
        run: pip install -r scripts/data/common/killed-in-gaza/requirements.txt

      - name: install dependencies
        run: bun install

      - name: run scripts & diff
        run: |
          python scripts/data/common/killed-in-gaza/generate_killed_list.py
          bun run gen-killed

      - name: commit vars
        id: commitvars
        run: |
          echo "currentdate=$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"
          echo "branchname=ci-workflow-$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        name: commit changes
        with:
          message: "daily: update for ${{ steps.commitvars.outputs.currentdate }}"
          new_branch: ${{ steps.commitvars.outputs.branchname }}
          push: true
